# Generated by Django 3.0.8 on 2020-07-03 04:47

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/', validators=[common.validators.validate_file_extension], verbose_name='Файл')),
                ('type', models.IntegerField(choices=[('1', 'Логотип бренда'), ('2', 'Иконка категории'), ('3', 'Изображение товара')], verbose_name='Тип файла')),
                ('is_public', models.BooleanField(default=True, verbose_name='Доступен к просмотру')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='market.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
